root = "."
tmp_dir = "tmp"
poll = true


[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
include_ext = ["go", "html"]
exclude_dir = ["tmp", "vendor"]
delay = 1000
kill_delay = "500ms"

[log]
time = false
