version: '3.8'

services:
  personal-website:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - APP_ENV=production
    volumes:
      # For persistent content (optional)
      - ./frontend/content:/app/frontend/content